apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-latest
  namespace: db
spec:
  serviceName: mysql-latest
  replicas: 3
  selector:
    matchLabels:
      app: mysql-latest
  template:
    metadata:
      labels:
        app: mysql-latest
    spec:
      containers:
      - name: mysql-latest
        image: mysql:latest
        env:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "itsasecret"
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql
            mountPath: "/var/lib/mysql"
          - name: dump
            mountPath: "/dump"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
      volumes:
        - name: mysql
          hostPath:
            path: "/mnt/mysqltestmigration/db"
        - name: dump
          hostPath:
            path: "/mnt/mysqltestmigration/dump"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-latest
  namespace: db
spec:
  selector:
    app: mysql-latest
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mysql-latest
  namespace: db
spec:
  entryPoints:
    - mysql
  routes:
  - match: HostSNI(`*`)
    services:
    - name: mysql-latest
      port: 3306
